//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soiree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public soiree()
        {
            this.utilisateur1 = new HashSet<utilisateur>();
        }
    
        public int idsoiree { get; set; }
        public string nom { get; set; }
        public System.DateTime date { get; set; }
        public string ville { get; set; }
        public int codePostale { get; set; }
        public string rue { get; set; }
        public Nullable<decimal> prixPrevente { get; set; }
        public Nullable<decimal> prixSurPlace { get; set; }
        public string description { get; set; }
        public int fk_utilisateur { get; set; }
    
        public virtual utilisateur utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<utilisateur> utilisateur1 { get; set; }
    }
}
